version: '3'
services:
  caddy:
    image: abiosoft/caddy:latest
    environment:
      - ACME_AGREE = true
      - CADDYPATH = /etc/caddycerts
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - $HOME/.caddy:/etc/caddycerts
  web:
    build: .
    ports:
      - 8084:80
    volumes:
     - ./files:/var/www/html/drupal/sites/default/files
  db:
    image: "mysql:5"
    restart: always
    volumes:
      - ./db:/var/lib/mysql
