version: '3'
services:
  web:
    build: .
    ports:
     - "8080:80"
  db:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'drupal_db'
    restart: always
    volumes:
      - ./db:/var/lib/mysql
